In [1]:
import numpy as np
a= np.array([3,5,6])
b=np.array([[1,4,4],[4,5,7]])
print(a.ndim,a.shape,a.dtype,b.dtype,b.ndim,b.shape)


1 (3,) int64 int64 2 (2, 3)


In [2]:
import numpy as np
a= np.array([3,5,6])
b=np.array([[1,4,4],[4,5,7]])
# print(a.ndim,a.shape,a.dtype,b.dtype,b.ndim,b.shape)
print(a+5,a*7,a**2)



[ 8 10 11] [21 35 42] [ 9 25 36]


In [3]:
import numpy as np
a= np.array([3,5,9])
b=np.array([[1,4,4],[4,5,7]])
print(np.sqrt(a),np.log(a),np.sin(a))
print(list(np.sqrt(a)))

[1.73205081 2.23606798 3.        ] [1.09861229 1.60943791 2.19722458] [ 0.14112001 -0.95892427  0.41211849]
[np.float64(1.7320508075688772), np.float64(2.23606797749979), np.float64(3.0)]


In [5]:
import numpy as np
a= np.array([3,5,9])
b=np.array([[1,4,4],[4,5,7]])
print(b[:,2],b[0,:])

[4 7] [1 4 4]


In [ ]:
import numpy as np
a= np.array([3,5,9])
b=np.array([[1,4,4],[4,5,7]])
x=np.arange(12)
print(x,x.reshape(3,4))
y=np.random.randint(1,100,10)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
